import { ReasoningScenario } from "../types";

export const SCENARIOS: ReasoningScenario[] = [
  {
    id: "fraud-ring",
    name: "Fraud Ring Discovery",
    complexityHops: 6,
    description: "Detecting multi-tier shell accounts cycling transactions back to illicit source via cyclic recurrence.",
    nodes: [
      { id: "n0", label: "Origin A₀", sublabel: "Seed Wallet", x: 0.14, y: 0.5 },
      { id: "n1", label: "Relay N₁", sublabel: "Layer 1 Shell", x: 0.28, y: 0.24 },
      { id: "n2", label: "Relay N₂", sublabel: "Layer 2 Mule", x: 0.50, y: 0.18 },
      { id: "n3", label: "Relay N₃", sublabel: "Layer 3 Offshore", x: 0.72, y: 0.24 },
      { id: "n4", label: "Proxy N₄", sublabel: "Mixer Router", x: 0.86, y: 0.5 },
      { id: "n5", label: "Sink N₅", sublabel: "Terminal Cache", x: 0.68, y: 0.76, isTarget: true },
      { id: "n6", label: "Decoy D₁", sublabel: "Benign Merchant", x: 0.32, y: 0.78, isNoise: true },
      { id: "n7", label: "Decoy D₂", sublabel: "Audit Blind", x: 0.50, y: 0.52, isNoise: true },
    ],
    edges: [
      { from: "n0", to: "n1", hopIndex: 1 },
      { from: "n1", to: "n2", hopIndex: 2 },
      { from: "n2", to: "n3", hopIndex: 3 },
      { from: "n3", to: "n4", hopIndex: 4 },
      { from: "n4", to: "n5", hopIndex: 5 },
      { from: "n5", to: "n0", hopIndex: 6 }, // cycle
      // Noise edges
      { from: "n1", to: "n6", hopIndex: 99, isNoise: true },
      { from: "n2", to: "n7", hopIndex: 99, isNoise: true },
      { from: "n6", to: "n7", hopIndex: 99, isNoise: true },
    ],
  },
  {
    id: "maze-traversal",
    name: "Live Maze Traversal",
    complexityHops: 7,
    description: "Deep graph pathfinding navigating dead ends, bifurcations, and backtracking until target exit is unlocked.",
    nodes: [
      { id: "m0", label: "ENTRANCE", sublabel: "Root Ingress", x: 0.10, y: 0.50 },
      { id: "m1", label: "FORK₁", sublabel: "Chamber A", x: 0.24, y: 0.28 },
      { id: "m2", label: "CORRIDOR", sublabel: "Hallway B", x: 0.40, y: 0.22 },
      { id: "m3", label: "JUNCTION", sublabel: "Nexus C", x: 0.58, y: 0.32 },
      { id: "m4", label: "PORTAL", sublabel: "Gate D", x: 0.74, y: 0.26 },
      { id: "m5", label: "SANCTUM", sublabel: "Ante-room", x: 0.88, y: 0.50 },
      { id: "m6", label: "EXIT", sublabel: "Goal Chamber", x: 0.76, y: 0.78, isTarget: true },
      { id: "mx1", label: "WALL A", sublabel: "Dead End", x: 0.32, y: 0.72, isNoise: true },
      { id: "mx2", label: "TRAP B", sublabel: "Cul-de-sac", x: 0.54, y: 0.70, isNoise: true },
    ],
    edges: [
      { from: "m0", to: "m1", hopIndex: 1 },
      { from: "m1", to: "m2", hopIndex: 2 },
      { from: "m2", to: "m3", hopIndex: 3 },
      { from: "m3", to: "m4", hopIndex: 4 },
      { from: "m4", to: "m5", hopIndex: 5 },
      { from: "m5", to: "m6", hopIndex: 6 },
      { from: "m6", to: "m0", hopIndex: 7 }, // loop validation
      { from: "m1", to: "mx1", hopIndex: 99, isNoise: true },
      { from: "m3", to: "mx2", hopIndex: 99, isNoise: true },
    ],
  },
  {
    id: "pointer-chasing",
    name: "8-Hop Pointer Chasing",
    complexityHops: 8,
    description: "Resolving recursive indirect memory dereference chains across key-value stores.",
    nodes: [
      { id: "p0", label: "PTR₀", sublabel: "Root Reg", x: 0.12, y: 0.5 },
      { id: "p1", label: "PTR₁", sublabel: "Addr 0x1A", x: 0.24, y: 0.25 },
      { id: "p2", label: "PTR₂", sublabel: "Addr 0x4F", x: 0.40, y: 0.20 },
      { id: "p3", label: "PTR₃", sublabel: "Addr 0x88", x: 0.58, y: 0.22 },
      { id: "p4", label: "PTR₄", sublabel: "Addr 0xBC", x: 0.74, y: 0.30 },
      { id: "p5", label: "PTR₅", sublabel: "Addr 0xD1", x: 0.88, y: 0.50 },
      { id: "p6", label: "PTR₆", sublabel: "Addr 0xFA", x: 0.72, y: 0.75 },
      { id: "p7", label: "PTR₇", sublabel: "Addr 0xFE", x: 0.48, y: 0.80 },
      { id: "p8", label: "VALUE", sublabel: "Payload", x: 0.26, y: 0.74, isTarget: true },
      { id: "px", label: "NULL", sublabel: "Dead End", x: 0.50, y: 0.50, isNoise: true },
    ],
    edges: [
      { from: "p0", to: "p1", hopIndex: 1 },
      { from: "p1", to: "p2", hopIndex: 2 },
      { from: "p2", to: "p3", hopIndex: 3 },
      { from: "p3", to: "p4", hopIndex: 4 },
      { from: "p4", to: "p5", hopIndex: 5 },
      { from: "p5", to: "p6", hopIndex: 6 },
      { from: "p6", to: "p7", hopIndex: 7 },
      { from: "p7", to: "p8", hopIndex: 8 },
      { from: "p2", to: "px", hopIndex: 99, isNoise: true },
      { from: "p4", to: "px", hopIndex: 99, isNoise: true },
    ],
  },
];
